from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
old='<meta content="v1295 · sudden-death-fresh-entry-editor" name="fc-build"/>'
new='<meta content="v1296 · ember-pending-upload-scope" name="fc-build"/>'
assert s.count(old)==1
s=s.replace(old,new,1)
old2='<meta content="Fixed sudden-death entry submission so tied finalists get a fresh current-round editor with the sudden-death deadline, rather than the closed original entry or old round media." name="fc-whatsnew"/>'
new2='<meta content="Fixed Ember upload-status guidance so it only reports the signed-in member’s recent moderation job, never another competitor’s stale pending entry, and calls out unusually slow reviews accurately." name="fc-whatsnew"/>'
assert s.count(old2)==1
s=s.replace(old2,new2,1)
oldblock="""    const pending = [\n      ...(state?.feedEntries || []),\n      ...(state?.myEntries || [])\n    ].find(e => ['pending','processing','reviewing','under_review'].includes(norm(e?.moderation_status || e?.review_state)));\n    if (pending) {\n      const ch = challenges.find(c => String(c.id) === String(pending.challenge_id));\n      add({\n        kind:'processing',\n        priority:60,\n        title:'Your upload is still being prepared',\n        text:ch?.title ? `${ch.title} will publish automatically when ready.` : 'It will publish automatically when ready.',\n        action:'View status',\n        challenge:ch,\n        run:()=>ch ? runChallengeV1221(ch) : closeDailyEmberV1221()\n      });\n    }\n"""
newblock="""    // v1296 — upload status must be scoped to the signed-in member. The old\n    // briefing searched feedEntries (which contains everyone) and took the first\n    // pending row it found, so a weeks-old pending video from another competitor\n    // could be announced as \"Your upload\". Keep only the member's own recent\n    // moderation work and do not resurrect abandoned/stale jobs indefinitely.\n    const meV1296 = String(state?.profile?.id || '');\n    const nowV1296 = Date.now();\n    const pending = [\n      ...(state?.myEntries || []),\n      ...(state?.feedEntries || [])\n    ]\n      .filter(e => meV1296 && String(e?.user_id || '') === meV1296)\n      .filter(e => ['pending','processing','reviewing','under_review','flagged','escalated'].includes(norm(e?.moderation_status || e?.review_state)))\n      .filter(e => {\n        const createdMs = Date.parse(e?.created_at || '');\n        if (!Number.isFinite(createdMs)) return false;\n        return nowV1296 - createdMs >= 0 && nowV1296 - createdMs <= 2 * 60 * 60 * 1000;\n      })\n      .sort((a,b) => Date.parse(b?.created_at || 0) - Date.parse(a?.created_at || 0))[0] || null;\n    if (pending) {\n      const ch = challenges.find(c => String(c.id) === String(pending.challenge_id));\n      const ageMsV1296 = nowV1296 - Date.parse(pending.created_at || '');\n      const slowV1296 = Number.isFinite(ageMsV1296) && ageMsV1296 > 10 * 60 * 1000;\n      add({\n        kind:'processing',\n        priority:60,\n        title:slowV1296 ? 'Your video review is taking longer than usual' : 'Your video is being checked',\n        text:slowV1296\n          ? (ch?.title ? `${ch.title} is saved and private while the review finishes.` : 'Your entry is saved and private while the review finishes.')\n          : (ch?.title ? `${ch.title} usually clears in seconds and will publish automatically if approved.` : 'Video review usually clears in seconds and publishes automatically if approved.'),\n        action:'Check status',\n        challenge:ch,\n        run:()=>ch ? runChallengeV1221(ch) : closeDailyEmberV1221()\n      });\n    }\n"""
assert s.count(oldblock)==1
s=s.replace(oldblock,newblock,1)
marker="<script>window.FC_V1296_VALIDATION={build:'v1296',pendingUploadScopedToSignedInUser:true,foreignFeedPendingExcluded:true,pendingJobsRecencyCapped:true,slowReviewCopyAfterTenMinutes:true,approvedConditionalCopy:true,v1295SuddenDeathPreserved:true};</script>\n"
assert s.count('</body>')==1
s=s.replace('</body>',marker+'</body>',1)
p.write_text(s,encoding='utf-8')
