/* v1325 — cinematic Spotlight replacement. */
(() => {
  const OLD_GENERATE = generateFlyer;
  const OLD_RENDER = renderPromoteFlyer;
  const gold=(ctx,x1,y1,x2,y2)=>{const g=ctx.createLinearGradient(x1,y1,x2,y2);g.addColorStop(0,'#fff0a6');g.addColorStop(.28,'#e7bd58');g.addColorStop(.60,'#b97b18');g.addColorStop(.83,'#f2cc68');g.addColorStop(1,'#fff6c4');return g;};
  const rr=(ctx,x,y,w,h,r,fill,stroke,width=1)=>{ctx.save();_roundRect(ctx,x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();}ctx.restore();};
  const label=it=>{const t=String(promoteState?.sourceMediaType||it?.media_type||'video').toLowerCase();return t==='image'||t==='photo'?'PHOTO':t==='audio'?'AUDIO':t==='text'?'TEXT':'VIDEO';};
  const profile=it=>promoteState?.heroAutoProfileV1324||it?.creator||state.profile||{};
  const name=(it,o)=>{let n=String(profile(it)?.name||o?.creatorName||'CHALLENGER').trim()||'CHALLENGER';if(!n.startsWith('@')&&!n.includes(' '))n='@'+n;return n.toUpperCase();};
  const count=it=>{try{const e=_cardEntriesFor(it);if(Array.isArray(e))return e.length;}catch(_){}const n=Number(state.entryCounts?.[it?.id]||0);return Number.isFinite(n)?Math.max(0,Math.round(n)):0;};
  const phase=(it,o)=>{const s=String(it?.computedStatus||computeChallengeStatus?.(it)||o?.phase||'').toLowerCase();return s==='voting'?'VOTING NOW':s==='closed'?'RESULTS FINAL':'ENTRIES OPEN';};
  const date=(it,o)=>{if(o?.deadlineDate)return String(o.deadlineDate).toUpperCase();const s=String(computeChallengeStatus?.(it)||o?.phase||'').toLowerCase(),d=s==='voting'?it?.voting_end:it?.submission_deadline;if(!d)return'OPEN';try{return new Date(d).toLocaleDateString(undefined,{month:'short',day:'numeric'}).toUpperCase();}catch(_){return'OPEN';}};
  const logoUrl=()=>{try{const raw=getComputedStyle(document.documentElement).getPropertyValue('--fc-approved-crowned-f').trim(),m=raw.match(/^url\\(["']?(.*?)["']?\\)$/);return m?m[1]:'';}catch(_){return'';}};
  const paint=(ctx,im,x,y,w,h,focus)=>{if(!im)return;const ratio=im.width/im.height,box=w/h;ctx.save();ctx.beginPath();_roundRect(ctx,x,y,w,h,28);ctx.clip();if(ratio<box*.78){const rb=Math.max(w/im.width,h/im.height)*1.18,bw=im.width*rb,bh=im.height*rb;ctx.save();try{ctx.filter='blur(34px) brightness(.38) saturate(.85)';}catch(_){}ctx.drawImage(im,x+(w-bw)/2,y+(h-bh)/2,bw,bh);ctx.restore();const rc=Math.min(w/im.width,h/im.height),cw=im.width*rc,ch=im.height*rc;ctx.drawImage(im,x+(w-cw)/2,y+(h-ch)/2,cw,ch);}else{const fx=Math.min(1,Math.max(0,focus?.x??.5)),fy=Math.min(1,Math.max(0,focus?.y??.5)),r=Math.max(w/im.width,h/im.height),dw=im.width*r,dh=im.height*r;ctx.drawImage(im,x+(w-dw)*fx,y+(h-dh)*fy,dw,dh);}ctx.restore();};
  async function draw(ctx,W,H,o){
    const it=promoteState?.item||state.promoteItem||{},p=profile(it),G2='#f0d47a',WHITE='#fff8e8',MUTED='#baa98f',HEAD='Anton, Impact, sans-serif',SANS='"DM Sans", system-ui, sans-serif';
    const bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#130c05');bg.addColorStop(.34,'#080503');bg.addColorStop(1,'#030201');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);
    const glow=ctx.createRadialGradient(W*.5,55,0,W*.5,55,W*.58);glow.addColorStop(0,'rgba(255,214,115,.22)');glow.addColorStop(.28,'rgba(210,145,35,.08)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,W,420);
    const beam=(x,r)=>{ctx.save();ctx.translate(x,-80);ctx.rotate(r);const g=ctx.createLinearGradient(0,0,0,520);g.addColorStop(0,'rgba(255,224,145,.26)');g.addColorStop(.55,'rgba(255,176,52,.045)');g.addColorStop(1,'rgba(255,176,52,0)');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-55,0);ctx.lineTo(55,0);ctx.lineTo(220,520);ctx.lineTo(-220,520);ctx.closePath();ctx.fill();ctx.restore();};beam(120,.20);beam(W-120,-.20);
    ctx.save();for(let i=0;i<34;i++){ctx.fillStyle=`rgba(238,185,71,${.05+(i%5)*.018})`;ctx.beginPath();ctx.arc((i*173)%W,78+((i*271)%(H-170)),1+(i%3)*.45,0,Math.PI*2);ctx.fill();}ctx.restore();rr(ctx,18,18,W-36,H-36,26,null,'rgba(220,173,68,.78)',3);rr(ctx,34,34,W-68,H-68,20,null,'rgba(255,243,196,.20)',1.5);
    let logo=null;const lu=logoUrl();if(lu){try{logo=await _loadImg(lu);}catch(_){}}if(logo){ctx.save();ctx.shadowColor='rgba(235,181,60,.38)';ctx.shadowBlur=28;ctx.drawImage(logo,W/2-44,48,88,88);ctx.restore();}
    ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=gold(ctx,190,0,W-190,0);ctx.shadowColor='rgba(229,173,58,.20)';ctx.shadowBlur=15;const brand='FLAMESCHALLENGE',bp=_fitText(ctx,brand,W-190,64,HEAD,'');ctx.font=`${bp}px ${HEAD}`;ctx.fillText(brand,W/2,164);ctx.shadowBlur=0;
    const media=label(it);ctx.fillStyle=WHITE;const mp=_fitTracked(ctx,media,400,36,SANS,'800',14);_trackedText(ctx,media,W/2,215,mp,SANS,'800',14);const vis=it?.is_public?'PUBLIC CHALLENGE':'PRIVATE CHALLENGE';rr(ctx,W/2-230,244,460,50,25,'rgba(5,3,2,.72)','rgba(242,214,132,.70)',2);ctx.fillStyle='#f4ddb0';ctx.font=`800 21px ${SANS}`;ctx.fillText(vis,W/2,270);
