    const hero={x:56,y:326,w:W-112,h:690};ctx.save();ctx.shadowColor='rgba(0,0,0,.70)';ctx.shadowBlur=34;ctx.shadowOffsetY=18;rr(ctx,hero.x,hero.y,hero.w,hero.h,30,'#0d0906','rgba(225,177,74,.78)',3);ctx.restore();if(o.heroImage)paint(ctx,o.heroImage,hero.x+4,hero.y+4,hero.w-8,hero.h-8,o.heroFocus);else{const m=ctx.createLinearGradient(hero.x,hero.y,hero.x+hero.w,hero.y+hero.h);m.addColorStop(0,'#211608');m.addColorStop(1,'#080604');rr(ctx,hero.x+4,hero.y+4,hero.w-8,hero.h-8,26,m);}
    ctx.save();ctx.beginPath();_roundRect(ctx,hero.x+4,hero.y+4,hero.w-8,hero.h-8,26);ctx.clip();const low=ctx.createLinearGradient(0,hero.y+hero.h*.55,0,hero.y+hero.h);low.addColorStop(0,'rgba(0,0,0,0)');low.addColorStop(.42,'rgba(0,0,0,.42)');low.addColorStop(1,'rgba(0,0,0,.94)');ctx.fillStyle=low;ctx.fillRect(hero.x,hero.y+hero.h*.50,hero.w,hero.h*.50);ctx.restore();rr(ctx,hero.x,hero.y,hero.w,hero.h,30,null,'rgba(255,236,171,.30)',1.25);
    if(media==='VIDEO'){const cx=W/2,cy=hero.y+hero.h*.47;ctx.save();ctx.fillStyle='rgba(0,0,0,.62)';ctx.strokeStyle='rgba(255,239,186,.95)';ctx.lineWidth=4;ctx.shadowColor='rgba(214,165,55,.30)';ctx.shadowBlur=22;ctx.beginPath();ctx.arc(cx,cy,66,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=WHITE;ctx.beginPath();ctx.moveTo(cx-14,cy-27);ctx.lineTo(cx-14,cy+27);ctx.lineTo(cx+31,cy);ctx.closePath();ctx.fill();ctx.restore();}
    const av={x:82,y:hero.y+hero.h-142,size:106};let ai=null,au=p?.avatar||p?.avatar_url||'';if(au&&/^(https?:|data:|blob:)/.test(au)){try{ai=await loadImageForFlyer(au);}catch(_){}}ctx.save();ctx.beginPath();ctx.arc(av.x+53,av.y+53,53,0,Math.PI*2);ctx.clip();if(ai)_paintHero(ctx,ai,av.x,av.y,av.size,av.size,'fill',{x:.5,y:.35});else{ctx.fillStyle='#17110b';ctx.fillRect(av.x,av.y,av.size,av.size);}ctx.restore();ctx.strokeStyle=G2;ctx.lineWidth=4;ctx.beginPath();ctx.arc(av.x+53,av.y+53,55,0,Math.PI*2);ctx.stroke();
    const nx=av.x+av.size+24,ny=av.y+41;ctx.textAlign='left';ctx.fillStyle=WHITE;const nm=name(it,o),np=_fitText(ctx,nm,575,44,HEAD,'');ctx.font=`${np}px ${HEAD}`;ctx.fillText(nm,nx,ny);ctx.fillStyle=G2;ctx.font=`700 23px ${SANS}`;ctx.fillText(media==='PHOTO'?'Photo Entry':media==='AUDIO'?'Audio Entry':media==='TEXT'?'Text Entry':'Video Entry',nx,ny+40);ctx.textAlign='right';ctx.fillStyle='rgba(255,248,232,.86)';ctx.font=`800 17px ${SANS}`;ctx.fillText('FEATURED ENTRY',hero.x+hero.w-34,hero.y+hero.h-56);
    ctx.strokeStyle='rgba(230,188,86,.28)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(70,1044);ctx.lineTo(W-70,1044);ctx.stroke();ctx.textAlign='left';ctx.fillStyle=G2;ctx.font=`800 18px ${SANS}`;ctx.fillText(String(it.category||o.kicker||'CHALLENGE').toUpperCase(),74,1090);ctx.fillStyle=WHITE;const title=String(o.title||it.title||'CHALLENGE').toUpperCase(),tp=_fitText(ctx,title,720,57,HEAD,'');ctx.font=`${tp}px ${HEAD}`;ctx.fillText(title,74,1140);ctx.fillStyle=MUTED;ctx.font=`700 18px ${SANS}`;ctx.fillText(phase(it,o),74,1184);ctx.fillStyle=G2;ctx.font=`700 42px ${HEAD}`;ctx.fillText(date(it,o),74,1240);
    const n=count(it),rx=W-78;ctx.textAlign='right';ctx.fillStyle=gold(ctx,W-320,0,W-70,0);ctx.font=`700 74px ${HEAD}`;ctx.fillText(String(n),rx,1160);ctx.fillStyle=WHITE;ctx.font=`800 19px ${SANS}`;ctx.fillText(n===1?'ENTRY':'ENTRIES',rx,1196);ctx.fillStyle=MUTED;ctx.font=`700 15px ${SANS}`;ctx.fillText('COMPETING',rx,1224);ctx.strokeStyle='rgba(226,179,75,.24)';ctx.beginPath();ctx.moveTo(W-300,1088);ctx.lineTo(W-300,1250);ctx.stroke();ctx.textAlign='center';ctx.fillStyle='rgba(255,247,223,.62)';const loop='ENTER  •  COMPETE  •  VOTE  •  WIN',lp=_fitTracked(ctx,loop,W-220,16,SANS,'800',3);_trackedText(ctx,loop,W/2,1302,lp,SANS,'800',3);
  }
  generateFlyer=async function(opts){if(opts?.style!=='spotlight')return OLD_GENERATE(opts);try{await document.fonts.ready;}catch(_){}const cv=document.createElement('canvas');cv.width=1080;cv.height=1350;const ctx=cv.getContext('2d');await draw(ctx,1080,1350,opts);return{dataUrl:cv.toDataURL('image/png'),blob:await new Promise(r=>cv.toBlob(r,'image/png'))};};
  renderPromoteFlyer=async function(){if(promoteState?.style!=='spotlight')return OLD_RENDER();const saved=promoteState.heroAutoUrl,m=promoteState.heroAutoMetaV1324;try{if(m?.media_type==='video'){const q=String(m.media_url||'').match(/\/([0-9a-f-]{36})\//i);if(q)promoteState.heroAutoUrl=`https://${BUNNY_CDN_HOST}/${q[1]}/preview.webp`;}return await OLD_RENDER();}finally{if(promoteState)promoteState.heroAutoUrl=saved;}};
  window.FC_V1325_VALIDATION={build:'v1325',cinematicSpotlightRenderer:true,canonicalCrownedF:true,spotlightUsesFeaturedSubmission:true,spotlightPrefersBunnyPreview:true,spotlightUsesEntryIdentity:true,spotlightIsFourByFive:true,otherFlyerStylesPreserved:true};
})();
